data_processing:
  question_col: Question
  answer_col: Answer
  train_data_size: 0.7
  val_data_size: 0.3

model_params:
  epochs: 5
  model_name: bert-base-uncased
  train_batch_size: 4
  val_batch_size: 4
